voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 248, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.cross_decomposition import train_test_split
ImportError: cannot import name 'train_test_split'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_memory'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation.check_memory import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_memory'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.column_or_1d'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation.column_or_1d import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.column_or_1d'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_is_fitted'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation.check_is_fitted import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_is_fitted'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.check_symmetric'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation.check_symmetric import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.check_symmetric'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.Birch'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.cluster.Birch import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.Birch'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cluster.KMeans'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.cluster.KMeans import train_test_split
ModuleNotFoundError: No module named 'sklearn.cluster.KMeans'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.validation.has_fit_parameter'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.validation.has_fit_parameter import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.validation.has_fit_parameter'; 'sklearn.utils.validation' is not a package
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.cross_decomposition.CCA'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.cross_decomposition.CCA import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_decomposition.CCA'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.utils.all_estimators'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
Traceback (most recent call last):
  File "extracting-results-by-visualizing-and-applying-svm.py", line 249, in <module>
    from sklearn.utils.all_estimators import train_test_split
ModuleNotFoundError: No module named 'sklearn.utils.all_estimators'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 248)])voice.csv

Total number ber of people involve in the test: 3168
Number of Male: 1584
Number of Female: 1584

[1 1 1 ... 0 0 0]
96.84542586750788
97.79179810725552
96.37223974763407

We got an accuracy of 96.84542586750788 by applying SVM using Linear Kernal 
We got an accuracy of 97.79179810725552 by applying SVM using RBF Kernal 
We got an accuracy of 96.37223974763407 by applying SVM using Polynomial Kernal 
[REPAIR EXEC TIME]: 48.28043270111084